# Generated by Django 3.2.3 on 2022-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_contacts_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.CharField(max_length=250, null=True)),
                ('Number_of_Section', models.CharField(max_length=250, null=True)),
                ('Website_Types', models.CharField(max_length=1, null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='File/')),
            ],
        ),
    ]
