# Generated by Django 3.2.3 on 2022-01-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0005_alter_frontend_orders_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontend_orders',
            old_name='File',
            new_name='Filez',
        ),
    ]
