# Generated by Django 3.2.3 on 2022-01-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0006_rename_file_frontend_orders_filez'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frontend_Orders',
        ),
    ]
