# Generated by Django 3.2.3 on 2022-01-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0008_file_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_system',
            new_name='Frontend_Order',
        ),
    ]
