# Generated by Django 3.2.3 on 2022-01-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0010_frontend_order_number_of_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_order',
            name='Website_Functionality',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
