# Generated by Django 3.2.3 on 2022-01-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0011_frontend_order_website_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_order',
            name='Price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
