# Generated by Django 3.2.3 on 2022-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0012_frontend_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_order',
            name='USer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
