# Generated by Django 3.2.3 on 2022-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0013_frontend_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_order',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
