# Generated by Django 3.2.3 on 2022-01-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0014_frontend_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Type', models.CharField(max_length=1, null=True)),
                ('Project_Plan', models.TextField(max_length=250)),
                ('Demo_File', models.FileField(max_length=1, upload_to='')),
            ],
        ),
    ]
