# Generated by Django 3.2.3 on 2022-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0015_hire_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_me',
            name='Demo_File',
            field=models.FileField(max_length=1, upload_to='hire_me/'),
        ),
    ]
