# Generated by Django 3.2.3 on 2022-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0016_alter_hire_me_demo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_me',
            name='Demo_File',
            field=models.FileField(blank=True, null=True, upload_to='new_file/'),
        ),
    ]
