# Generated by Django 3.2.3 on 2022-01-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0017_alter_hire_me_demo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_me',
            name='EMail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hire_me',
            name='USer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
