# Generated by Django 3.2.3 on 2022-03-01 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0018_auto_20220114_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_order',
            name='USer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
