# Generated by Django 3.2.3 on 2022-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0026_alter_frontend_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='frontend_order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hire_me',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
