# Generated by Django 3.2.3 on 2022-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0027_auto_20220304_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_order',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
