# Generated by Django 3.2.3 on 2022-03-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0029_alter_frontend_order_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=250, null=True)),
                ('Number_of_Section', models.CharField(max_length=250, null=True)),
                ('Website_Functionality', models.CharField(max_length=1, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='new_file/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('USer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_backend_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
