# Generated by Django 3.2.3 on 2022-03-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0031_rename_price_backend_order_backendprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend_order',
            name='BackendPrice',
        ),
        migrations.RemoveField(
            model_name='backend_order',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='backend_order',
            name='Number_of_Section',
        ),
        migrations.RemoveField(
            model_name='backend_order',
            name='Website_Functionality',
        ),
    ]
