# Generated by Django 3.2.3 on 2022-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0034_auto_20220304_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend_order',
            old_name='Demo_project_File',
            new_name='Project_File',
        ),
    ]
