# Generated by Django 3.2.3 on 2022-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0036_alter_backend_order_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_order',
            name='Project_File',
            field=models.FileField(blank=True, null=True, upload_to='1_backend_files/'),
        ),
        migrations.AlterField(
            model_name='frontend_order',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='0_frontend_files/'),
        ),
    ]
