# Generated by Django 3.2.3 on 2022-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0037_auto_20220304_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend_order',
            name='Service_Type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
