# Generated by Django 3.2.3 on 2022-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0038_backend_order_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_order',
            name='Service_Type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
