# Generated by Django 3.2.3 on 2022-03-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0039_frontend_order_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend_order',
            old_name='Backend_Price',
            new_name='Price',
        ),
        migrations.AlterField(
            model_name='backend_order',
            name='Project_File',
            field=models.FileField(blank=True, null=True, upload_to='2_complete_website_files/'),
        ),
        migrations.AlterField(
            model_name='backend_order',
            name='USer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_complete_website_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
