# Generated by Django 3.2.3 on 2022-03-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0040_auto_20220304_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend_order',
            old_name='Price',
            new_name='Backend_Price',
        ),
        migrations.AlterField(
            model_name='backend_order',
            name='Project_File',
            field=models.FileField(blank=True, null=True, upload_to='1_backend_files/'),
        ),
        migrations.AlterField(
            model_name='backend_order',
            name='USer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_backend_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Complete_Website_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Type', models.CharField(max_length=250, null=True)),
                ('Price', models.CharField(max_length=250, null=True)),
                ('Number_Of_Section', models.CharField(max_length=250, null=True)),
                ('Website_Functionality', models.CharField(max_length=1, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Project_File', models.FileField(blank=True, null=True, upload_to='2_complete_website_files/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('USer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_complete_website_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
