# Generated by Django 3.2.3 on 2022-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0043_remove_frontend_order_mnu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Manu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
