# Generated by Django 3.2.3 on 2022-03-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0045_frontend_order_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_order',
            name='Website_Functionality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complete_website_orders',
            name='Website_Functionality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='frontend_order',
            name='Website_Functionality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
