# Generated by Django 3.2.3 on 2022-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0049_alter_frontend_order_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_order',
            name='order_message',
        ),
        migrations.AddField(
            model_name='frontend_order',
            name='order_message',
            field=models.ManyToManyField(to='business_app.Message_Manu'),
        ),
    ]
