# Generated by Django 3.2.3 on 2022-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0050_auto_20220313_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_order',
            name='order_message',
            field=models.ManyToManyField(null=True, to='business_app.Message_Manu'),
        ),
    ]
