# Generated by Django 3.2.3 on 2022-03-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0051_alter_frontend_order_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_order',
            name='order_message',
        ),
    ]
