# Generated by Django 3.2.3 on 2022-03-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0052_remove_frontend_order_order_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message_Manu',
        ),
    ]
