# Generated by Django 3.2.3 on 2022-03-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0055_frontend_order_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_order',
            name='order_message',
        ),
        migrations.AddField(
            model_name='frontend_order',
            name='order_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_app.message_manu'),
        ),
    ]
