# Generated by Django 3.2.3 on 2022-03-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0059_alter_frontend_order_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend_order',
            name='order_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message1', to='business_app.message_manu'),
        ),
        migrations.AddField(
            model_name='complete_website_orders',
            name='order_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message2', to='business_app.message_manu'),
        ),
    ]
