# Generated by Django 3.2.3 on 2022-03-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0062_auto_20220314_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend_order',
            name='Per_section_Price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
