# Generated by Django 3.2.3 on 2022-03-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0065_complete_website_orders_per_section_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('USer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
