# Generated by Django 3.2.3 on 2022-03-25 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0066_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='Profile_picture',
            field=models.ImageField(blank=True, default='3_profile_picture/avatar.png', null=True, upload_to='3_profile_picture/'),
        ),
        migrations.AlterField(
            model_name='profile_picture',
            name='USer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_propic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Frontend_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=1, null=True)),
                ('USer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='frontend_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
