# Generated by Django 3.2.3 on 2022-03-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0067_auto_20220326_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_rating',
            name='USer',
        ),
        migrations.AlterField(
            model_name='frontend_rating',
            name='Rating',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
