# Generated by Django 3.2.3 on 2022-03-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0070_alter_frontend_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_rating',
            name='USer',
        ),
    ]
