# Generated by Django 3.2.3 on 2022-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0073_auto_20220326_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_rating',
            name='Rating',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
