# Generated by Django 3.2.3 on 2022-03-28 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0075_alter_frontend_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='USer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_propic', to=settings.AUTH_USER_MODEL),
        ),
    ]
