# Generated by Django 3.2.3 on 2022-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0076_alter_profile_picture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='3_profile_picture/'),
        ),
    ]
