# Generated by Django 3.2.3 on 2022-04-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0077_alter_profile_picture_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='Demo_File',
            field=models.FileField(blank=True, null=True, upload_to='4_hire_me/'),
        ),
    ]
