# Generated by Django 3.2.3 on 2022-04-24 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0078_auto_20220423_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend_rating',
            name='USer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='frontend_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
