# Generated by Django 3.2.3 on 2022-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0080_backend_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_rating',
            name='Rating',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
