# Generated by Django 3.2.3 on 2022-04-24 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0081_alter_backend_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_rating',
            name='Rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
