# Generated by Django 3.2.3 on 2022-04-24 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0083_alter_backend_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_Website_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(null=True)),
                ('Feedback', models.TextField(max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('USer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='complete_website_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
