# Generated by Django 3.2.3 on 2022-04-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0084_complete_website_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend_rating',
            name='profile_Picture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_pic', to='business_app.profile_picture'),
        ),
    ]
