# Generated by Django 3.2.3 on 2022-04-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0087_frontend_rating_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend_rating',
            name='profile_Picture',
        ),
    ]
