# Generated by Django 3.2.3 on 2022-04-25 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0088_remove_frontend_rating_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_me',
            name='USer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hireME', to=settings.AUTH_USER_MODEL),
        ),
    ]
