# Generated by Django 3.2.3 on 2022-05-10 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0091_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Likes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faqLIKE', to=settings.AUTH_USER_MODEL),
        ),
    ]
