# Generated by Django 3.2.3 on 2022-05-10 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0092_alter_faq_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='Likes',
        ),
        migrations.AddField(
            model_name='faq',
            name='Likes',
            field=models.ManyToManyField(default=None, related_name='faqLIKE', to=settings.AUTH_USER_MODEL),
        ),
    ]
