# Generated by Django 3.2.3 on 2022-05-11 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0094_auto_20220511_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='faqLIKES', to=settings.AUTH_USER_MODEL),
        ),
    ]
