# Generated by Django 3.2.3 on 2022-05-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0096_alter_faq_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='likes',
        ),
        migrations.AddField(
            model_name='faq',
            name='likes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqLIKES', to=settings.AUTH_USER_MODEL),
        ),
    ]
