# Generated by Django 3.2.3 on 2022-05-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0098_auto_20220513_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='likes',
        ),
        migrations.CreateModel(
            name='FAQlikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name_faq_question', to='business_app.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
