# Generated by Django 3.2.3 on 2022-05-13 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_app', '0099_auto_20220513_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='FAQlikes',
            new_name='Likes',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='faq',
            new_name='blog',
        ),
    ]
