# Generated by Django 3.2.3 on 2022-05-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0100_auto_20220513_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_blog', to='business_app.blog'),
        ),
    ]
